export { default as C_TagsView } from './index.vue'
export { useTagsView } from './useTagsView'
export type { UseTagsViewOptions } from './useTagsView'
export type { ContextMenuLabels } from './types'
export type { TagItem } from '../_shared/public'
