/* 原有的常量数据 */
export const fieldTypes = [
  { label: "BIGINT", value: "BIGINT" },
  { label: "INT", value: "INT" },
  { label: "SMALLINT", value: "SMALLINT" },
  { label: "TINYINT", value: "TINYINT" },
  { label: "VARCHAR(50)", value: "VARCHAR(50)" },
  { label: "VARCHAR(100)", value: "VARCHAR(100)" },
  { label: "VARCHAR(255)", value: "VARCHAR(255)" },
  { label: "CHAR(10)", value: "CHAR(10)" },
  { label: "TEXT", value: "TEXT" },
  { label: "LONGTEXT", value: "LONGTEXT" },
  { label: "DATETIME", value: "DATETIME" },
  { label: "TIMESTAMP", value: "TIMESTAMP" },
  { label: "DATE", value: "DATE" },
  { label: "TIME", value: "TIME" },
  { label: "DECIMAL(10,2)", value: "DECIMAL(10,2)" },
  { label: "FLOAT", value: "FLOAT" },
  { label: "DOUBLE", value: "DOUBLE" },
  { label: "BOOLEAN", value: "BOOLEAN" },
  { label: "JSON", value: "JSON" },
];
